#!/bin/sh

EXPECTED=`logname`
if [ $? -ne 0 ]
then
        exit 77
fi
OUT=`logname/logname`
if [ $? -ne 0 ]
then
	echo T1 failed
	exit 1
fi
if [ "X$OUT" != "X$EXPECTED" ]
then
	echo T2 failed
	exit 1
fi
